[package]
name = "Learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.13"
bevy = "0.9"
device_query = "0.2"
rand = "0.8"